api_label = '5954581278:AAGqLr-SedHyM1RPHrn9G4Sy_FgmMGvO16E'
reg = 'reg'
change_name_log = "Вы уже зарегестрированы, но можете поменять имя."
ask_name_log = "Как вас зовут?"
yes_log = 'Да'
no_log = 'Нет'
yes_eng = 'yes'
no_eng = 'no'
your_name_log = 'Вас зовут '
ques_mark = '?'
view_note = 'view_note'
first_reg_log = "Чтобы работать с заметками нужно сначала зарегестрироваться, введите /reg"
view_note_log = "Просмотр заметки. Введите название заметки, которую хотите посмотреть: "
delete_note = 'delete_note'
back_log = '/back'
cancellation = 'Отменено.'
view_note_list = 'view_note_list'
name_list_log = "Список названий заметок: \n"
does_not_exist_log = "Такое название не существует. Введите другое: "
already_exists_log = "Такое название уже существует. Введите другое: "
delete_note_log = "Удаление заметки. Введите название заметки, которую хотите удалить: "
deleted_log = "Удалено."
edit_note = 'edit_note'
editing_note_log = "Редактирование заметки. Введите название: "
enter_text_log = "Введите новый текст заметки "
written = "Записано."
add_note = 'add_note'
new_creation_log =  "Создание новой заметки. Введите название: "
unique_name_and_enter_log = "Круто, это название уникальное. Теперь можете ввести что-то в поле заметки: "
name_saved = 'Ваше имя сохранено'
writereg = 'Напишите /reg и введите правильные данные'
start_log = 'start'
help_log = 'help'
description_log =  "Я - бот, который может хранить твои заметки.\nНапиши /reg чтобы зарегестрироваться (обязательно для использования бота)\n/add_note чтобы добавить заметку\n/delete_note чтобы удалить заметку\n/edit_note чтобы редактировать заметку\n/view_note_list чтобы посмотреть список заметок\n/view_note чтобы посмотреть заметку\n/back чтобы отменить последнее действие"
